export const REPOS_SEARCH_REQUEST = "REPOS_SEARCH_REQUEST";
export const REPOS_SEARCH_SUCCESS = "REPOS_SEARCH_SUCCESS";
export const REPOS_SEARCH_EMPTY = "REPOS_SEARCH_EMPTY";
export const REPOS_SEARCH_NOT_FOUND = "REPOS_SEARCH_NOT_FOUND";
export const REPOS_CLEAR = "REPOS_CLEAR";

export const HISTORY_ADD_ITEM = "HISTORY_ADD_ITEM";
export const HISTORY_REMOVE_ITEM = "HISTORY_REMOVE_ITEM";
export const HISTORY_CLEAR = "HISTORY_CLEAR";
export const HISTORY_SHOW = "HISTORY_SHOW";
export const HISTORY_HIDE = "HISTORY_HIDE";